name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        since_last_remote_commit: 'true'

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        # 使用更稳定的 SSH 连接方式
        ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 ${SERVER_USER}@${SERVER_HOST} << 'EOF'
          set -e  # 任何命令失败则退出

          echo "hello"
          
          source /opt/clash/script/common.sh
          source /opt/clash/script/clashctl.sh
          watch_proxy

          echo "loaded"
          
          # 开启代理
          clash on

          echo "clash on "
          
          # 进入项目目录
          cd /root/bot/AL-1S-Bot
          
          # 拉取最新代码
          git pull origin main
          
          # 关闭代理
          clash off
          
          echo "clash off"
          
          # 检查 requirements.txt 是否在本次提交中发生变化
          if echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -q "requirements.txt"; then
            echo "requirements.txt 已变更，需要重新构建..."
            # 执行构建并启动
            docker compose up -d --build
            # 等待一段时间让容器启动
            sleep 15
            # 输出 napcat 日志以供扫码登录
            echo "=== Napcat 日志 ==="
            docker logs napcat --tail=50
          else
            echo "requirements.txt 未变更，仅重启 nonebot 服务..."
            # 仅重启 nonebot 容器
            docker restart nonebot
            # 输出重启结果
            echo "=== 服务状态 ==="
            docker ps
          fi
          
          # 输出最终的服务状态和最近日志
          echo "=== 最终服务状态 ==="
          docker ps
          echo "=== NoneBot 最近日志 ==="
          docker logs nonebot --tail=20
        EOF
