name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        since_last_remote_commit: 'true'

    - name: SSH to Server and Deploy
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script_stop: true
        script: |
          # 开启代理
          clash on
          
          # 进入项目目录并拉取最新代码
          cd /root/bot/AL-1S-Bot
          git pull origin main
          
          # 关闭代理
          clash off
          
          # 检查 requirements.txt 是否在本次提交中发生变化
          if echo "${{ steps.changed-files.outputs.all_changed_files }}" | grep -q "requirements.txt"; then
            echo "requirements.txt 已变更，需要重新构建..."
            # 执行构建并启动
            docker-compose up -d --build
            # 等待一段时间让容器启动
            sleep 10
            # 输出 napcat 日志以供扫码登录
            echo "=== Napcat 日志 ==="
            docker-compose logs napcat --tail=50
          else
            echo "requirements.txt 未变更，仅重启 nonebot 服务..."
            # 仅重启 nonebot 容器
            docker-compose restart nonebot
            # 输出重启结果
            echo "=== 服务状态 ==="
            docker-compose ps
          fi
          
          # 输出最终的服务状态和最近日志
          echo "=== 最终服务状态 ==="
          docker-compose ps
          echo "=== NoneBot 最近日志 ==="
          docker-compose logs nonebot --tail=20
